name = "telegram-mcq-bot"
main = "src/worker.ts"
compatibility_date = "2024-01-01"
account_id = "your_account_id_here"

# Use workers.dev subdomain for deployment
workers_dev = true

[[kv_namespaces]]
binding = "STATE"
id = "your_kv_namespace_id_here"

[vars]
TZ = "Asia/Kolkata"

[triggers]
crons = ["0 * * * *"]
